### ISSUE TITLE
Error when editing settings on new install

### ISSUE THREAD

**Issue by bfjare** [guilty-as/hubspot-connector#1]
Click on settings link in control panel throws this error.

`Call to a member function all() on null
`

<img width="1654" alt="screen shot 2019-01-26 at 6 10 10 pm" src="https://user-images.githubusercontent.com/11744681/51794690-a7c41500-2195-11e9-96e6-80ec72dc6d0c.png">

**Comment by HelgeSverre** [comment]
which version are you using?

**Comment by bfjare** [comment]
"guilty/hubspot-connector": "1.0.2",

**Comment by HelgeSverre** [comment]
try 1.0.3

**Comment by bfjare** [comment]
Confirming that works
